package com.tiredex.yoko.utils;

/**
 * List of valid MIME Type aka Internet Media Types aka Content Types.  List copied from http://www.freeformatter.com/mime-types-list.html#mime-types-list
 * on 8/2/16.
 * 
 * @author AlainG
 *
 */
public enum MimeTypesEnum {

	x3d ("3D Crossword Plugin", ".x3d", "application/vnd.hzn-3d-crossword"),
	threegp ("3GP", ".3gp", "video/3gpp"),
	threeg2 ("3GP2", ".3g2", "video/3gpp2"),
	mseq ("3GPP MSEQ File", ".mseq", "application/vnd.mseq"),
	pwn ("3M Post It Notes", ".pwn", "application/vnd.3m.post-it-notes"),
	plb ("3rd Generation Partnership Project - Pic Large", ".plb", "application/vnd.3gpp.pic-bw-large"),
	psb ("3rd Generation Partnership Project - Pic Small", ".psb", "application/vnd.3gpp.pic-bw-small"),
	pvb ("3rd Generation Partnership Project - Pic Var", ".pvb", "application/vnd.3gpp.pic-bw-var"),
	tcap ("3rd Generation Partnership Project - Transaction Capabilities Application Part", ".tcap", "application/vnd.3gpp2.tcap"),
	sevenz ("7-Zip", ".7z", "application/x-7z-compressed"),
	abw ("AbiWord", ".abw", "application/x-abiword"),
	ace ("Ace Archive", ".ace", "application/x-ace-compressed"),
	acc ("Active Content Compression", ".acc", "application/vnd.americandynamics.acc"),
	acu ("ACU Cobol", ".acu", "application/vnd.acucobol"),
	atc ("ACU Cobol", ".atc", "application/vnd.acucorp"),
	adp ("Adaptive differential pulse-code modulation", ".adp", "audio/adpcm"),
	aab ("Adobe (Macropedia) Authorware - Binary File", ".aab", "application/x-authorware-bin"),
	aam ("Adobe (Macropedia) Authorware - Map", ".aam", "application/x-authorware-map"),
	aas ("Adobe (Macropedia) Authorware - Segment File", ".aas", "application/x-authorware-seg"),
	air ("Adobe AIR Application", ".air", "application/vnd.adobe.air-application-installer-package+zip"),
	swf ("Adobe Flash", ".swf", "application/x-shockwave-flash"),
	fxp ("Adobe Flex Project", ".fxp", "application/vnd.adobe.fxp"),
	pdf ("Adobe Portable Document Format", ".pdf", "application/pdf"),
	ppd ("Adobe PostScript Printer Description File Format", ".ppd", "application/vnd.cups-ppd"),
	dir ("Adobe Shockwave Player", ".dir", "application/x-director"),
	xdp ("Adobe XML Data Package", ".xdp", "application/vnd.adobe.xdp+xml"),
	xfdf ("Adobe XML Forms Data Format", ".xfdf", "application/vnd.adobe.xfdf"),
	aac ("Advanced Audio Coding (AAC)", ".aac", "audio/x-aac"),
	ahead ("Ahead AIR Application", ".ahead", "application/vnd.ahead.space"),
	azf ("AirZip FileSECURE", ".azf", "application/vnd.airzip.filesecure.azf"),
	azs ("AirZip FileSECURE", ".azs", "application/vnd.airzip.filesecure.azs"),
	azw ("Amazon Kindle eBook format", ".azw", "application/vnd.amazon.ebook"),
	ami ("AmigaDE", ".ami", "application/vnd.amiga.ami"),
	NA ("Andrew Toolkit", "N/A", "application/andrew-inset"),
	apk ("Android Package Archive", ".apk", "application/vnd.android.package-archive"),
	cii ("ANSER-WEB Terminal Client - Certificate Issue", ".cii", "application/vnd.anser-web-certificate-issue-initiation"),
	fti ("ANSER-WEB Terminal Client - Web Funds Transfer", ".fti", "application/vnd.anser-web-funds-transfer-initiation"),
	atx ("Antix Game Player", ".atx", "application/vnd.antix.game-component"),
	mpkg ("Apple Installer Package", ".mpkg", "application/vnd.apple.installer+xml"),
	aw ("Applixware", ".aw", "application/applixware"),
	les ("Archipelago Lesson Player", ".les", "application/vnd.hhe.lesson-player"),
	swi ("Arista Networks Software Image", ".swi", "application/vnd.aristanetworks.swi"),
	s ("Assembler Source File", ".s", "text/x-asm"),
	atomcat ("Atom Publishing Protocol", ".atomcat", "application/atomcat+xml"),
	atomsvc ("Atom Publishing Protocol Service Document", ".atomsvc", "application/atomsvc+xml"),
	atom ("Atom Syndication Format", ".atom", "application/atom+xml"),
	xml ("Atom Syndication Format", ".xml", "application/atom+xml"),
	ac ("Attribute Certificate", ".ac", "application/pkix-attr-cert"),
	aif ("Audio Interchange File Format", ".aif", "audio/x-aiff"),
	avi ("Audio Video Interleave (AVI)", ".avi", "video/x-msvideo"),
	aep ("Audiograph", ".aep", "application/vnd.audiograph"),
	dxf ("AutoCAD DXF", ".dxf", "image/vnd.dxf"),
	dwf ("Autodesk Design Web Format (DWF)", ".dwf", "model/vnd.dwf"),
	par ("BAS Partitur Format", ".par", "text/plain-bas"),
	bcpio ("Binary CPIO Archive", ".bcpio", "application/x-bcpio"),
	bin ("Binary Data", ".bin", "application/octet-stream"),
	bmp ("Bitmap Image File", ".bmp", "image/bmp"),
	torrent ("BitTorrent", ".torrent", "application/x-bittorrent"),
	cod ("Blackberry COD File", ".cod", "application/vnd.rim.cod"),
	mpm ("Blueice Research Multipass", ".mpm", "application/vnd.blueice.multipass"),
	bmi ("BMI Drawing Data Interchange", ".bmi", "application/vnd.bmi"),
	sh ("Bourne Shell Script", ".sh", "application/x-sh"),
	btif ("BTIF", ".btif", "image/prs.btif"),
	rep ("BusinessObjects", ".rep", "application/vnd.businessobjects"),
	bz ("Bzip Archive", ".bz", "application/x-bzip"),
	bz2 ("Bzip2 Archive", ".bz2", "application/x-bzip2"),
	csh ("C Shell Script", ".csh", "application/x-csh"),
	c ("C Source File", ".c", "text/x-c"),
	cdxml ("CambridgeSoft Chem Draw", ".cdxml", "application/vnd.chemdraw+xml"),
	css ("Cascading Style Sheets (CSS)", ".css", "text/css"),
	cdx ("ChemDraw eXchange file", ".cdx", "chemical/x-cdx"),
	cml ("Chemical Markup Language", ".cml", "chemical/x-cml"),
	csml ("Chemical Style Markup Language", ".csml", "chemical/x-csml"),
	cdbcmsg ("CIM Database", ".cdbcmsg", "application/vnd.contact.cmsg"),
	cla ("Claymore Data Files", ".cla", "application/vnd.claymore"),
	c4g ("Clonk Game", ".c4g", "application/vnd.clonk.c4group"),
	sub ("Close Captioning - Subtitle", ".sub", "image/vnd.dvb.subtitle"),
	cdmia ("Cloud Data Management Interface (CDMI) - Capability", ".cdmia", "application/cdmi-capability"),
	cdmic ("Cloud Data Management Interface (CDMI) - Contaimer", ".cdmic", "application/cdmi-container"),
	cdmid ("Cloud Data Management Interface (CDMI) - Domain", ".cdmid", "application/cdmi-domain"),
	cdmio ("Cloud Data Management Interface (CDMI) - Object", ".cdmio", "application/cdmi-object"),
	cdmiq ("Cloud Data Management Interface (CDMI) - Queue", ".cdmiq", "application/cdmi-queue"),
	c11amc ("ClueTrust CartoMobile - Config", ".c11amc", "application/vnd.cluetrust.cartomobile-config"),
	c11amz ("ClueTrust CartoMobile - Config Package", ".c11amz", "application/vnd.cluetrust.cartomobile-config-pkg"),
	ras ("CMU Image", ".ras", "image/x-cmu-raster"),
	dae ("COLLADA", ".dae", "model/vnd.collada+xml"),
	csv ("Comma-Seperated Values", ".csv", "text/csv"),
	cpt ("Compact Pro", ".cpt", "application/mac-compactpro"),
	wmlc ("Compiled Wireless Markup Language (WMLC)", ".wmlc", "application/vnd.wap.wmlc"),
	cgm ("Computer Graphics Metafile", ".cgm", "image/cgm"),
	ice ("CoolTalk", ".ice", "x-conference/x-cooltalk"),
	cmx ("Corel Metafile Exchange (CMX)", ".cmx", "image/x-cmx"),
	xar ("CorelXARA", ".xar", "application/vnd.xara"),
	cmc ("CosmoCaller", ".cmc", "application/vnd.cosmocaller"),
	cpio ("CPIO Archive", ".cpio", "application/x-cpio"),
	clkx ("CrickSoftware - Clicker", ".clkx", "application/vnd.crick.clicker"),
	clkk ("CrickSoftware - Clicker - Keyboard", ".clkk", "application/vnd.crick.clicker.keyboard"),
	clkp ("CrickSoftware - Clicker - Palette", ".clkp", "application/vnd.crick.clicker.palette"),
	clkt ("CrickSoftware - Clicker - Template", ".clkt", "application/vnd.crick.clicker.template"),
	clkw ("CrickSoftware - Clicker - Wordbank", ".clkw", "application/vnd.crick.clicker.wordbank"),
	wbs ("Critical Tools - PERT Chart EXPERT", ".wbs", "application/vnd.criticaltools.wbs+xml"),
	cryptonote ("CryptoNote", ".cryptonote", "application/vnd.rig.cryptonote"),
	cif ("Crystallographic Interchange Format", ".cif", "chemical/x-cif"),
	cmdf ("CrystalMaker Data Format", ".cmdf", "chemical/x-cmdf"),
	cu ("CU-SeeMe", ".cu", "application/cu-seeme"),
	cww ("CU-Writer", ".cww", "application/prs.cww"),
	curl ("Curl - Applet", ".curl", "text/vnd.curl"),
	dcurl ("Curl - Detached Applet", ".dcurl", "text/vnd.curl.dcurl"),
	mcurl ("Curl - Manifest File", ".mcurl", "text/vnd.curl.mcurl"),
	scurl ("Curl - Source Code", ".scurl", "text/vnd.curl.scurl"),
	car ("CURL Applet", ".car", "application/vnd.curl.car"),
	pcurl ("CURL Applet", ".pcurl", "application/vnd.curl.pcurl"),
	cmp ("CustomMenu", ".cmp", "application/vnd.yellowriver-custom-menu"),
	dssc ("Data Structure for the Security Suitability of Cryptographic Algorithms", ".dssc", "application/dssc+der"),
	xdssc ("Data Structure for the Security Suitability of Cryptographic Algorithms", ".xdssc", "application/dssc+xml"),
	deb ("Debian Package", ".deb", "application/x-debian-package"),
	uva ("DECE Audio", ".uva", "audio/vnd.dece.audio"),
	uvi ("DECE Graphic", ".uvi", "image/vnd.dece.graphic"),
	uvh ("DECE High Definition Video", ".uvh", "video/vnd.dece.hd"),
	uvm ("DECE Mobile Video", ".uvm", "video/vnd.dece.mobile"),
	uvu ("DECE MP4", ".uvu", "video/vnd.uvvu.mp4"),
	uvp ("DECE PD Video", ".uvp", "video/vnd.dece.pd"),
	uvs ("DECE SD Video", ".uvs", "video/vnd.dece.sd"),
	uvv ("DECE Video", ".uvv", "video/vnd.dece.video"),
	dvi ("Device Independent File Format (DVI)", ".dvi", "application/x-dvi"),
	seed ("Digital Siesmograph Networks - SEED Datafiles", ".seed", "application/vnd.fdsn.seed"),
	dtb ("Digital Talking Book", ".dtb", "application/x-dtbook+xml"),
	res ("Digital Talking Book - Resource File", ".res", "application/x-dtbresource+xml"),
	ait ("Digital Video Broadcasting", ".ait", "application/vnd.dvb.ait"),
	svc ("Digital Video Broadcasting", ".svc", "application/vnd.dvb.service"),
	eol ("Digital Winds Music", ".eol", "audio/vnd.digital-winds"),
	djvu ("DjVu", ".djvu", "image/vnd.djvu"),
	dtd ("Document Type Definition", ".dtd", "application/xml-dtd"),
	mlp ("Dolby Meridian Lossless Packing", ".mlp", "application/vnd.dolby.mlp"),
	wad ("Doom Video Game", ".wad", "application/x-doom"),
	dpg ("DPGraph", ".dpg", "application/vnd.dpgraph"),
	dra ("DRA Audio", ".dra", "audio/vnd.dra"),
	dfac ("DreamFactory", ".dfac", "application/vnd.dreamfactory"),
	dts ("DTS Audio", ".dts", "audio/vnd.dts"),
	dtshd ("DTS High Definition Audio", ".dtshd", "audio/vnd.dts.hd"),
	dwg ("DWG Drawing", ".dwg", "image/vnd.dwg"),
	geo ("DynaGeo", ".geo", "application/vnd.dynageo"),
	es ("ECMAScript", ".es", "application/ecmascript"),
	mag ("EcoWin Chart", ".mag", "application/vnd.ecowin.chart"),
	mmr ("EDMICS 2000", ".mmr", "image/vnd.fujixerox.edmics-mmr"),
	rlc ("EDMICS 2000", ".rlc", "image/vnd.fujixerox.edmics-rlc"),
	exi ("Efficient XML Interchange", ".exi", "application/exi"),
	mgz ("EFI Proteus", ".mgz", "application/vnd.proteus.magazine"),
	epub ("Electronic Publication", ".epub", "application/epub+zip"),
	eml ("Email Message", ".eml", "message/rfc822"),
	nml ("Enliven Viewer", ".nml", "application/vnd.enliven"),
	xpr ("Express by Infoseek", ".xpr", "application/vnd.is-xpr"),
	xif ("eXtended Image File Format (XIFF)", ".xif", "image/vnd.xiff"),
	xfdl ("Extensible Forms Description Language", ".xfdl", "application/vnd.xfdl"),
	emma ("Extensible MultiModal Annotation", ".emma", "application/emma+xml"),
	ez2 ("EZPix Secure Photo Album", ".ez2", "application/vnd.ezpix-album"),
	ez3 ("EZPix Secure Photo Album", ".ez3", "application/vnd.ezpix-package"),
	fst ("FAST Search & Transfer ASA", ".fst", "image/vnd.fst"),
	fvt ("FAST Search & Transfer ASA", ".fvt", "video/vnd.fvt"),
	fbs ("FastBid Sheet", ".fbs", "image/vnd.fastbidsheet"),
	fe_launch ("FCS Express Layout Link", ".fe_launch", "application/vnd.denovo.fcselayout-link"),
	f4v ("Flash Video", ".f4v", "video/x-f4v"),
	flv ("Flash Video", ".flv", "video/x-flv"),
	fpx ("FlashPix", ".fpx", "image/vnd.fpx"),
	npx ("FlashPix", ".npx", "image/vnd.net-fpx"),
	flx ("FLEXSTOR", ".flx", "text/vnd.fmi.flexstor"),
	fli ("FLI/FLC Animation Format", ".fli", "video/x-fli"),
	ftc ("FluxTime Clip", ".ftc", "application/vnd.fluxtime.clip"),
	fdf ("Forms Data Format", ".fdf", "application/vnd.fdf"),
	f ("Fortran Source File", ".f", "text/x-fortran"),
	mif ("FrameMaker Interchange Format", ".mif", "application/vnd.mif"),
	fm ("FrameMaker Normal Format", ".fm", "application/vnd.framemaker"),
	fh ("FreeHand MX", ".fh", "image/x-freehand"),
	fsc ("Friendly Software Corporation", ".fsc", "application/vnd.fsc.weblaunch"),
	fnc ("Frogans Player", ".fnc", "application/vnd.frogans.fnc"),
	ltf ("Frogans Player", ".ltf", "application/vnd.frogans.ltf"),
	ddd ("Fujitsu - Xerox 2D CAD Data", ".ddd", "application/vnd.fujixerox.ddd"),
	xdw ("Fujitsu - Xerox DocuWorks", ".xdw", "application/vnd.fujixerox.docuworks"),
	xbd ("Fujitsu - Xerox DocuWorks Binder", ".xbd", "application/vnd.fujixerox.docuworks.binder"),
	oas ("Fujitsu Oasys", ".oas", "application/vnd.fujitsu.oasys"),
	oa2 ("Fujitsu Oasys", ".oa2", "application/vnd.fujitsu.oasys2"),
	oa3 ("Fujitsu Oasys", ".oa3", "application/vnd.fujitsu.oasys3"),
	fg5 ("Fujitsu Oasys", ".fg5", "application/vnd.fujitsu.oasysgp"),
	bh2 ("Fujitsu Oasys", ".bh2", "application/vnd.fujitsu.oasysprs"),
	spl ("FutureSplash Animator", ".spl", "application/x-futuresplash"),
	fzs ("FuzzySheet", ".fzs", "application/vnd.fuzzysheet"),
	g3 ("G3 Fax Image", ".g3", "image/g3fax"),
	gmx ("GameMaker ActiveX", ".gmx", "application/vnd.gmx"),
	gtw ("Gen-Trix Studio", ".gtw", "model/vnd.gtw"),
	txd ("Genomatix Tuxedo Framework", ".txd", "application/vnd.genomatix.tuxedo"),
	ggb ("GeoGebra", ".ggb", "application/vnd.geogebra.file"),
	ggt ("GeoGebra", ".ggt", "application/vnd.geogebra.tool"),
	gdl ("Geometric Description Language (GDL)", ".gdl", "model/vnd.gdl"),
	gex ("GeoMetry Explorer", ".gex", "application/vnd.geometry-explorer"),
	gxt ("GEONExT and JSXGraph", ".gxt", "application/vnd.geonext"),
	g2w ("GeoplanW", ".g2w", "application/vnd.geoplan"),
	g3w ("GeospacW", ".g3w", "application/vnd.geospace"),
	gsf ("Ghostscript Font", ".gsf", "application/x-font-ghostscript"),
	bdf ("Glyph Bitmap Distribution Format", ".bdf", "application/x-font-bdf"),
	gtar ("GNU Tar Files", ".gtar", "application/x-gtar"),
	texinfo ("GNU Texinfo Document", ".texinfo", "application/x-texinfo"),
	gnumeric ("Gnumeric", ".gnumeric", "application/x-gnumeric"),
	kml ("Google Earth - KML", ".kml", "application/vnd.google-earth.kml+xml"),
	kmz ("Google Earth - Zipped KML", ".kmz", "application/vnd.google-earth.kmz"),
	gqf ("GrafEq", ".gqf", "application/vnd.grafeq"),
	gif ("Graphics Interchange Format", ".gif", "image/gif"),
	gv ("Graphviz", ".gv", "text/vnd.graphviz"),
	gac ("Groove - Account", ".gac", "application/vnd.groove-account"),
	ghf ("Groove - Help", ".ghf", "application/vnd.groove-help"),
	gim ("Groove - Identity Message", ".gim", "application/vnd.groove-identity-message"),
	grv ("Groove - Injector", ".grv", "application/vnd.groove-injector"),
	gtm ("Groove - Tool Message", ".gtm", "application/vnd.groove-tool-message"),
	tpl ("Groove - Tool Template", ".tpl", "application/vnd.groove-tool-template"),
	vcg ("Groove - Vcard", ".vcg", "application/vnd.groove-vcard"),
	h261 ("H.261", ".h261", "video/h261"),
	h263 ("H.263", ".h263", "video/h263"),
	h264 ("H.264", ".h264", "video/h264"),
	hpid ("Hewlett Packard Instant Delivery", ".hpid", "application/vnd.hp-hpid"),
	hps ("Hewlett-Packard's WebPrintSmart", ".hps", "application/vnd.hp-hps"),
	hdf ("Hierarchical Data Format", ".hdf", "application/x-hdf"),
	rip ("Hit'n'Mix", ".rip", "audio/vnd.rip"),
	hbci ("Homebanking Computer Interface (HBCI)", ".hbci", "application/vnd.hbci"),
	jlt ("HP Indigo Digital Press - Job Layout Languate", ".jlt", "application/vnd.hp-jlyt"),
	pcl ("HP Printer Command Language", ".pcl", "application/vnd.hp-pcl"),
	hpgl ("HP-GL/2 and HP RTL", ".hpgl", "application/vnd.hp-hpgl"),
	hvs ("HV Script", ".hvs", "application/vnd.yamaha.hv-script"),
	hvd ("HV Voice Dictionary", ".hvd", "application/vnd.yamaha.hv-dic"),
	hvp ("HV Voice Parameter", ".hvp", "application/vnd.yamaha.hv-voice"),
	sfdhdstx ("Hydrostatix Master Suite", ".sfd-hdstx", "application/vnd.hydrostatix.sof-data"),
	stk ("Hyperstudio", ".stk", "application/hyperstudio"),
	hal ("Hypertext Application Language", ".hal", "application/vnd.hal+xml"),
	html ("HyperText Markup Language (HTML)", ".html", "text/html"),
	irm ("IBM DB2 Rights Manager", ".irm", "application/vnd.ibm.rights-management"),
	sc ("IBM Electronic Media Management System - Secure Container", ".sc", "application/vnd.ibm.secure-container"),
	ics ("iCalendar", ".ics", "text/calendar"),
	icc ("ICC profile", ".icc", "application/vnd.iccprofile"),
	ico ("Icon Image", ".ico", "image/x-icon"),
	igl ("igLoader", ".igl", "application/vnd.igloader"),
	ief ("Image Exchange Format", ".ief", "image/ief"),
	ivp ("ImmerVision PURE Players", ".ivp", "application/vnd.immervision-ivp"),
	ivu ("ImmerVision PURE Players", ".ivu", "application/vnd.immervision-ivu"),
	rif ("IMS Networks", ".rif", "application/reginfo+xml"),
	threedml ("In3D - 3DML", ".3dml", "text/vnd.in3d.3dml"),
	spot ("In3D - 3DML", ".spot", "text/vnd.in3d.spot"),
	igs ("Initial Graphics Exchange Specification (IGES)", ".igs", "model/iges"),
	i2g ("Interactive Geometry Software", ".i2g", "application/vnd.intergeo"),
	cdy ("Interactive Geometry Software Cinderella", ".cdy", "application/vnd.cinderella"),
	xpw ("Intercon FormNet", ".xpw", "application/vnd.intercon.formnet"),
	fcs ("International Society for Advancement of Cytometry", ".fcs", "application/vnd.isac.fcs"),
	ipfix ("Internet Protocol Flow Information Export", ".ipfix", "application/ipfix"),
	cer ("Internet Public Key Infrastructure - Certificate", ".cer", "application/pkix-cert"),
	pki ("Internet Public Key Infrastructure - Certificate Management Protocole", ".pki", "application/pkixcmp"),
	crl ("Internet Public Key Infrastructure - Certificate Revocation Lists", ".crl", "application/pkix-crl"),
	pkipath ("Internet Public Key Infrastructure - Certification Path", ".pkipath", "application/pkix-pkipath"),
	igm ("IOCOM Visimeet", ".igm", "application/vnd.insors.igm"),
	rcprofile ("IP Unplugged Roaming Client", ".rcprofile", "application/vnd.ipunplugged.rcprofile"),
	irp ("iRepository / Lucidoc Editor", ".irp", "application/vnd.irepository.package+xml"),
	jad ("J2ME App Descriptor", ".jad", "text/vnd.sun.j2me.app-descriptor"),
	jar ("Java Archive", ".jar", "application/java-archive"),
	jar2 ("Java Archive", ".jar", "application/x-zip-compressed"),
	javaclass ("Java Bytecode File", ".class", "application/java-vm"),
	jnlp ("Java Network Launching Protocol", ".jnlp", "application/x-java-jnlp-file"),
	ser ("Java Serialized Object", ".ser", "application/java-serialized-object"),
	java ("Java Source File", ".java", "text/x-java-source,java"),
	js ("JavaScript", ".js", "application/javascript"),
	json ("JavaScript Object Notation (JSON)", ".json", "application/json"),
	joda ("Joda Archive", ".joda", "application/vnd.joost.joda-archive"),
	jpm ("JPEG 2000 Compound Image File Format", ".jpm", "video/jpm"),
	jpeg ("JPEG Image", ".jpeg", "image/jpeg"),
	jpg ("JPEG Image", ".jpg", "image/jpeg"),
	jpgv ("JPGVideo", ".jpgv", "video/jpeg"),
	ktz ("Kahootz", ".ktz", "application/vnd.kahootz"),
	mmd ("Karaoke on Chipnuts Chipsets", ".mmd", "application/vnd.chipnuts.karaoke-mmd"),
	karbon ("KDE KOffice Office Suite - Karbon", ".karbon", "application/vnd.kde.karbon"),
	chrt ("KDE KOffice Office Suite - KChart", ".chrt", "application/vnd.kde.kchart"),
	kfo ("KDE KOffice Office Suite - Kformula", ".kfo", "application/vnd.kde.kformula"),
	flw ("KDE KOffice Office Suite - Kivio", ".flw", "application/vnd.kde.kivio"),
	kon ("KDE KOffice Office Suite - Kontour", ".kon", "application/vnd.kde.kontour"),
	kpr ("KDE KOffice Office Suite - Kpresenter", ".kpr", "application/vnd.kde.kpresenter"),
	ksp ("KDE KOffice Office Suite - Kspread", ".ksp", "application/vnd.kde.kspread"),
	kwd ("KDE KOffice Office Suite - Kword", ".kwd", "application/vnd.kde.kword"),
	htke ("Kenamea App", ".htke", "application/vnd.kenameaapp"),
	kia ("Kidspiration", ".kia", "application/vnd.kidspiration"),
	kne ("Kinar Applications", ".kne", "application/vnd.kinar"),
	sse ("Kodak Storyshare", ".sse", "application/vnd.kodak-descriptor"),
	lasxml ("Laser App Enterprise", ".lasxml", "application/vnd.las.las+xml"),
	latex ("LaTeX", ".latex", "application/x-latex"),
	lbd ("Life Balance - Desktop Edition", ".lbd", "application/vnd.llamagraphics.life-balance.desktop"),
	lbe ("Life Balance - Exchange Format", ".lbe", "application/vnd.llamagraphics.life-balance.exchange+xml"),
	jam ("Lightspeed Audio Lab", ".jam", "application/vnd.jam"),
	one23 ("Lotus 1-2-3", "0.123", "application/vnd.lotus-1-2-3"),
	apr ("Lotus Approach", ".apr", "application/vnd.lotus-approach"),
	pre ("Lotus Freelance", ".pre", "application/vnd.lotus-freelance"),
	nsf ("Lotus Notes", ".nsf", "application/vnd.lotus-notes"),
	org ("Lotus Organizer", ".org", "application/vnd.lotus-organizer"),
	scm ("Lotus Screencam", ".scm", "application/vnd.lotus-screencam"),
	lwp ("Lotus Wordpro", ".lwp", "application/vnd.lotus-wordpro"),
	lvp ("Lucent Voice", ".lvp", "audio/vnd.lucent.voice"),
	m3u ("M3U (Multimedia Playlist)", ".m3u", "audio/x-mpegurl"),
	m4v ("M4v", ".m4v", "video/x-m4v"),
	hqx ("Macintosh BinHex 4.0", ".hqx", "application/mac-binhex40"),
	portpkg ("MacPorts Port System", ".portpkg", "application/vnd.macports.portpkg"),
	mgp ("MapGuide DBXML", ".mgp", "application/vnd.osgeo.mapguide.package"),
	mrc ("MARC Formats", ".mrc", "application/marc"),
	mrcx ("MARC21 XML Schema", ".mrcx", "application/marcxml+xml"),
	mxf ("Material Exchange Format", ".mxf", "application/mxf"),
	nbp ("Mathematica Notebook Player", ".nbp", "application/vnd.wolfram.player"),
	ma ("Mathematica Notebooks", ".ma", "application/mathematica"),
	mathml ("Mathematical Markup Language", ".mathml", "application/mathml+xml"),
	mbox ("Mbox database files", ".mbox", "application/mbox"),
	mc1 ("MedCalc", ".mc1", "application/vnd.medcalcdata"),
	mscml ("Media Server Control Markup Language", ".mscml", "application/mediaservercontrol+xml"),
	cdkey ("MediaRemote", ".cdkey", "application/vnd.mediastation.cdkey"),
	mwf ("Medical Waveform Encoding Format", ".mwf", "application/vnd.mfer"),
	mfm ("Melody Format for Mobile Platform", ".mfm", "application/vnd.mfmp"),
	msh ("Mesh Data Type", ".msh", "model/mesh"),
	mads ("Metadata Authority Description Schema", ".mads", "application/mads+xml"),
	mets ("Metadata Encoding and Transmission Standard", ".mets", "application/mets+xml"),
	mods ("Metadata Object Description Schema", ".mods", "application/mods+xml"),
	meta4 ("Metalink", ".meta4", "application/metalink4+xml"),
	potm ("Micosoft PowerPoint - Macro-Enabled Template File", ".potm", "application/vnd.ms-powerpoint.template.macroenabled.12"),
	docm ("Micosoft Word - Macro-Enabled Document", ".docm", "application/vnd.ms-word.document.macroenabled.12"),
	dotm ("Micosoft Word - Macro-Enabled Template", ".dotm", "application/vnd.ms-word.template.macroenabled.12"),
	mcd ("Micro CADAM Helix D&D", ".mcd", "application/vnd.mcd"),
	flo ("Micrografx", ".flo", "application/vnd.micrografx.flo"),
	igx ("Micrografx iGrafx Professional", ".igx", "application/vnd.micrografx.igx"),
	es3 ("MICROSEC e-Szign¢", ".es3", "application/vnd.eszigno3+xml"),
	mdb ("Microsoft Access", ".mdb", "application/x-msaccess"),
	accdb ("Microsoft Access", ".accdb", "application/msaccess"),
	asf ("Microsoft Advanced Systems Format (ASF)", ".asf", "video/x-ms-asf"),
	exe ("Microsoft Application", ".exe", "application/x-msdownload"),
	cil ("Microsoft Artgalry", ".cil", "application/vnd.ms-artgalry"),
	cab ("Microsoft Cabinet File", ".cab", "application/vnd.ms-cab-compressed"),
	ims ("Microsoft Class Server", ".ims", "application/vnd.ms-ims"),
	application ("Microsoft ClickOnce", ".application", "application/x-ms-application"),
	clp ("Microsoft Clipboard Clip", ".clp", "application/x-msclip"),
	mdi ("Microsoft Document Imaging Format", ".mdi", "image/vnd.ms-modi"),
	eot ("Microsoft Embedded OpenType", ".eot", "application/vnd.ms-fontobject"),
	xls ("Microsoft Excel", ".xls", "application/vnd.ms-excel"),
	xlam ("Microsoft Excel - Add-In File", ".xlam", "application/vnd.ms-excel.addin.macroenabled.12"),
	xlsb ("Microsoft Excel - Binary Workbook", ".xlsb", "application/vnd.ms-excel.sheet.binary.macroenabled.12"),
	xltm ("Microsoft Excel - Macro-Enabled Template File", ".xltm", "application/vnd.ms-excel.template.macroenabled.12"),
	xlsm ("Microsoft Excel - Macro-Enabled Workbook", ".xlsm", "application/vnd.ms-excel.sheet.macroenabled.12"),
	chm ("Microsoft Html Help File", ".chm", "application/vnd.ms-htmlhelp"),
	crd ("Microsoft Information Card", ".crd", "application/x-mscardfile"),
	lrm ("Microsoft Learning Resource Module", ".lrm", "application/vnd.ms-lrm"),
	mvb ("Microsoft MediaView", ".mvb", "application/x-msmediaview"),
	mny ("Microsoft Money", ".mny", "application/x-msmoney"),
	pptx ("Microsoft Office - OOXML - Presentation", ".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
	sldx ("Microsoft Office - OOXML - Presentation (Slide)", ".sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide"),
	ppsx ("Microsoft Office - OOXML - Presentation (Slideshow)", ".ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow"),
	potx ("Microsoft Office - OOXML - Presentation Template", ".potx", "application/vnd.openxmlformats-officedocument.presentationml.template"),
	xlsx ("Microsoft Office - OOXML - Spreadsheet", ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
	xltx ("Microsoft Office - OOXML - Spreadsheet Teplate", ".xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template"),
	docx ("Microsoft Office - OOXML - Word Document", ".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
	dotx ("Microsoft Office - OOXML - Word Document Template", ".dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"),
	obd ("Microsoft Office Binder", ".obd", "application/x-msbinder"),
	thmx ("Microsoft Office System Release Theme", ".thmx", "application/vnd.ms-officetheme"),
	onetoc ("Microsoft OneNote", ".onetoc", "application/onenote"),
	pya ("Microsoft PlayReady Ecosystem", ".pya", "audio/vnd.ms-playready.media.pya"),
	pyv ("Microsoft PlayReady Ecosystem Video", ".pyv", "video/vnd.ms-playready.media.pyv"),
	ppt ("Microsoft PowerPoint", ".ppt", "application/vnd.ms-powerpoint"),
	ppam ("Microsoft PowerPoint - Add-in file", ".ppam", "application/vnd.ms-powerpoint.addin.macroenabled.12"),
	sldm ("Microsoft PowerPoint - Macro-Enabled Open XML Slide", ".sldm", "application/vnd.ms-powerpoint.slide.macroenabled.12"),
	pptm ("Microsoft PowerPoint - Macro-Enabled Presentation File", ".pptm", "application/vnd.ms-powerpoint.presentation.macroenabled.12"),
	ppsm ("Microsoft PowerPoint - Macro-Enabled Slide Show File", ".ppsm", "application/vnd.ms-powerpoint.slideshow.macroenabled.12"),
	mpp ("Microsoft Project", ".mpp", "application/vnd.ms-project"),
	pub ("Microsoft Publisher", ".pub", "application/x-mspublisher"),
	scd ("Microsoft Schedule+", ".scd", "application/x-msschedule"),
	xap ("Microsoft Silverlight", ".xap", "application/x-silverlight-app"),
	stl ("Microsoft Trust UI Provider - Certificate Trust Link", ".stl", "application/vnd.ms-pki.stl"),
	cat ("Microsoft Trust UI Provider - Security Catalog", ".cat", "application/vnd.ms-pki.seccat"),
	vsd ("Microsoft Visio", ".vsd", "application/vnd.visio"),
	wm ("Microsoft Windows Media", ".wm", "video/x-ms-wm"),
	wma ("Microsoft Windows Media Audio", ".wma", "audio/x-ms-wma"),
	wax ("Microsoft Windows Media Audio Redirector", ".wax", "audio/x-ms-wax"),
	wmx ("Microsoft Windows Media Audio/Video Playlist", ".wmx", "video/x-ms-wmx"),
	wmd ("Microsoft Windows Media Player Download Package", ".wmd", "application/x-ms-wmd"),
	wpl ("Microsoft Windows Media Player Playlist", ".wpl", "application/vnd.ms-wpl"),
	wmz ("Microsoft Windows Media Player Skin Package", ".wmz", "application/x-ms-wmz"),
	wmv ("Microsoft Windows Media Video", ".wmv", "video/x-ms-wmv"),
	wvx ("Microsoft Windows Media Video Playlist", ".wvx", "video/x-ms-wvx"),
	wmf ("Microsoft Windows Metafile", ".wmf", "application/x-msmetafile"),
	trm ("Microsoft Windows Terminal Services", ".trm", "application/x-msterminal"),
	doc ("Microsoft Word", ".doc", "application/msword"),
	wri ("Microsoft Wordpad", ".wri", "application/x-mswrite"),
	wps ("Microsoft Works", ".wps", "application/vnd.ms-works"),
	xbap ("Microsoft XAML Browser Application", ".xbap", "application/x-ms-xbap"),
	xps ("Microsoft XML Paper Specification", ".xps", "application/vnd.ms-xpsdocument"),
	mid ("MIDI - Musical Instrument Digital Interface", ".mid", "audio/midi"),
	mpy ("MiniPay", ".mpy", "application/vnd.ibm.minipay"),
	afp ("MO:DCA-P", ".afp", "application/vnd.ibm.modcap"),
	rms ("Mobile Information Device Profile", ".rms", "application/vnd.jcp.javame.midlet-rms"),
	tmo ("MobileTV", ".tmo", "application/vnd.tmobile-livetv"),
	prc ("Mobipocket", ".prc", "application/x-mobipocket-ebook"),
	mbk ("Mobius Management Systems - Basket file", ".mbk", "application/vnd.mobius.mbk"),
	dis ("Mobius Management Systems - Distribution Database", ".dis", "application/vnd.mobius.dis"),
	plc ("Mobius Management Systems - Policy Definition Language File", ".plc", "application/vnd.mobius.plc"),
	mqy ("Mobius Management Systems - Query File", ".mqy", "application/vnd.mobius.mqy"),
	msl ("Mobius Management Systems - Script Language", ".msl", "application/vnd.mobius.msl"),
	txf ("Mobius Management Systems - Topic Index File", ".txf", "application/vnd.mobius.txf"),
	daf ("Mobius Management Systems - UniversalArchive", ".daf", "application/vnd.mobius.daf"),
	fly ("mod_fly / fly.cgi", ".fly", "text/vnd.fly"),
	mpc ("Mophun Certificate", ".mpc", "application/vnd.mophun.certificate"),
	mpn ("Mophun VM", ".mpn", "application/vnd.mophun.application"),
	mj2 ("Motion JPEG 2000", ".mj2", "video/mj2"),
	mpga ("MPEG Audio", ".mpga", "audio/mpeg"),
	mxu ("MPEG Url", ".mxu", "video/vnd.mpegurl"),
	mpeg ("MPEG Video", ".mpeg", "video/mpeg"),
	m21 ("MPEG-21", ".m21", "application/mp21"),
	mp4a ("MPEG-4 Audio", ".mp4a", "audio/mp4"),
	mp4 ("MPEG-4 Video", ".mp4", "video/mp4"),
	mp4b ("MPEG4", ".mp4", "application/mp4"),
	m3u8 ("Multimedia Playlist Unicode", ".m3u8", "application/vnd.apple.mpegurl"),
	mus ("MUsical Score Interpreted Code Invented for the ASCII designation of Notation", ".mus", "application/vnd.musician"),
	msty ("Muvee Automatic Video Editing", ".msty", "application/vnd.muvee.style"),
	mxml ("MXML", ".mxml", "application/xv+xml"),
	ngdat ("N-Gage Game Data", ".ngdat", "application/vnd.nokia.n-gage.data"),
	ngage ("N-Gage Game Installer", ".n-gage", "application/vnd.nokia.n-gage.symbian.install"),
	ncx ("Navigation Control file for XML (for ePub)", ".ncx", "application/x-dtbncx+xml"),
	nc ("Network Common Data Form (NetCDF)", ".nc", "application/x-netcdf"),
	nlu ("neuroLanguage", ".nlu", "application/vnd.neurolanguage.nlu"),
	dna ("New Moon Liftoff/DNA", ".dna", "application/vnd.dna"),
	nnd ("NobleNet Directory", ".nnd", "application/vnd.noblenet-directory"),
	nns ("NobleNet Sealer", ".nns", "application/vnd.noblenet-sealer"),
	nnw ("NobleNet Web", ".nnw", "application/vnd.noblenet-web"),
	rpst ("Nokia Radio Application - Preset", ".rpst", "application/vnd.nokia.radio-preset"),
	rpss ("Nokia Radio Application - Preset", ".rpss", "application/vnd.nokia.radio-presets"),
	n3 ("Notation3", ".n3", "text/n3"),
	edm ("Novadigm's RADIA and EDM products", ".edm", "application/vnd.novadigm.edm"),
	edx ("Novadigm's RADIA and EDM products", ".edx", "application/vnd.novadigm.edx"),
	ext ("Novadigm's RADIA and EDM products", ".ext", "application/vnd.novadigm.ext"),
	gph ("NpGraphIt", ".gph", "application/vnd.flographit"),
	ecelp4800 ("Nuera ECELP 4800", ".ecelp4800", "audio/vnd.nuera.ecelp4800"),
	ecelp7470 ("Nuera ECELP 7470", ".ecelp7470", "audio/vnd.nuera.ecelp7470"),
	ecelp9600 ("Nuera ECELP 9600", ".ecelp9600", "audio/vnd.nuera.ecelp9600"),
	oda ("Office Document Architecture", ".oda", "application/oda"),
	ogx ("Ogg", ".ogx", "application/ogg"),
	oga ("Ogg Audio", ".oga", "audio/ogg"),
	ogv ("Ogg Video", ".ogv", "video/ogg"),
	dd2 ("OMA Download Agents", ".dd2", "application/vnd.oma.dd2+xml"),
	oth ("Open Document Text Web", ".oth", "application/vnd.oasis.opendocument.text-web"),
	opf ("Open eBook Publication Structure", ".opf", "application/oebps-package+xml"),
	qbo ("Open Financial Exchange", ".qbo", "application/vnd.intu.qbo"),
	oxt ("Open Office Extension", ".oxt", "application/vnd.openofficeorg.extension"),
	osf ("Open Score Format", ".osf", "application/vnd.yamaha.openscoreformat"),
	weba ("Open Web Media Project - Audio", ".weba", "audio/webm"),
	webm ("Open Web Media Project - Video", ".webm", "video/webm"),
	odc ("OpenDocument Chart", ".odc", "application/vnd.oasis.opendocument.chart"),
	otc ("OpenDocument Chart Template", ".otc", "application/vnd.oasis.opendocument.chart-template"),
	odb ("OpenDocument Database", ".odb", "application/vnd.oasis.opendocument.database"),
	odf ("OpenDocument Formula", ".odf", "application/vnd.oasis.opendocument.formula"),
	odft ("OpenDocument Formula Template", ".odft", "application/vnd.oasis.opendocument.formula-template"),
	odg ("OpenDocument Graphics", ".odg", "application/vnd.oasis.opendocument.graphics"),
	otg ("OpenDocument Graphics Template", ".otg", "application/vnd.oasis.opendocument.graphics-template"),
	odi ("OpenDocument Image", ".odi", "application/vnd.oasis.opendocument.image"),
	oti ("OpenDocument Image Template", ".oti", "application/vnd.oasis.opendocument.image-template"),
	odp ("OpenDocument Presentation", ".odp", "application/vnd.oasis.opendocument.presentation"),
	otp ("OpenDocument Presentation Template", ".otp", "application/vnd.oasis.opendocument.presentation-template"),
	ods ("OpenDocument Spreadsheet", ".ods", "application/vnd.oasis.opendocument.spreadsheet"),
	ots ("OpenDocument Spreadsheet Template", ".ots", "application/vnd.oasis.opendocument.spreadsheet-template"),
	odt ("OpenDocument Text", ".odt", "application/vnd.oasis.opendocument.text"),
	odm ("OpenDocument Text Master", ".odm", "application/vnd.oasis.opendocument.text-master"),
	ott ("OpenDocument Text Template", ".ott", "application/vnd.oasis.opendocument.text-template"),
	ktx ("OpenGL Textures (KTX)", ".ktx", "image/ktx"),
	sxc ("OpenOffice - Calc (Spreadsheet)", ".sxc", "application/vnd.sun.xml.calc"),
	stc ("OpenOffice - Calc Template (Spreadsheet)", ".stc", "application/vnd.sun.xml.calc.template"),
	sxd ("OpenOffice - Draw (Graphics)", ".sxd", "application/vnd.sun.xml.draw"),
	std ("OpenOffice - Draw Template (Graphics)", ".std", "application/vnd.sun.xml.draw.template"),
	sxi ("OpenOffice - Impress (Presentation)", ".sxi", "application/vnd.sun.xml.impress"),
	sti ("OpenOffice - Impress Template (Presentation)", ".sti", "application/vnd.sun.xml.impress.template"),
	sxm ("OpenOffice - Math (Formula)", ".sxm", "application/vnd.sun.xml.math"),
	sxw ("OpenOffice - Writer (Text - HTML)", ".sxw", "application/vnd.sun.xml.writer"),
	sxg ("OpenOffice - Writer (Text - HTML)", ".sxg", "application/vnd.sun.xml.writer.global"),
	stw ("OpenOffice - Writer Template (Text - HTML)", ".stw", "application/vnd.sun.xml.writer.template"),
	otf ("OpenType Font File", ".otf", "application/x-font-otf"),
	osfpvg ("OSFPVG", ".osfpvg", "application/vnd.yamaha.openscoreformat.osfpvg+xml"),
	dp ("OSGi Deployment Package", ".dp", "application/vnd.osgi.dp"),
	pdb ("PalmOS Data", ".pdb", "application/vnd.palm"),
	p ("Pascal Source File", ".p", "text/x-pascal"),
	paw ("PawaaFILE", ".paw", "application/vnd.pawaafile"),
	pclxl ("PCL 6 Enhanced (Formely PCL XL)", ".pclxl", "application/vnd.hp-pclxl"),
	efif ("Pcsel eFIF File", ".efif", "application/vnd.picsel"),
	pcx ("PCX Image", ".pcx", "image/x-pcx"),
	psd ("Photoshop Document", ".psd", "image/vnd.adobe.photoshop"),
	prf ("PICSRules", ".prf", "application/pics-rules"),
	pic ("PICT Image", ".pic", "image/x-pict"),
	chat ("pIRCh", ".chat", "application/x-chat"),
	p10 ("PKCS #10 - Certification Request Standard", ".p10", "application/pkcs10"),
	p12 ("PKCS #12 - Personal Information Exchange Syntax Standard", ".p12", "application/x-pkcs12"),
	p7m ("PKCS #7 - Cryptographic Message Syntax Standard", ".p7m", "application/pkcs7-mime"),
	p7s ("PKCS #7 - Cryptographic Message Syntax Standard", ".p7s", "application/pkcs7-signature"),
	p7r ("PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)", ".p7r", "application/x-pkcs7-certreqresp"),
	p7b ("PKCS #7 - Cryptographic Message Syntax Standard (Certificates)", ".p7b", "application/x-pkcs7-certificates"),
	p8 ("PKCS #8 - Private-Key Information Syntax Standard", ".p8", "application/pkcs8"),
	plf ("PocketLearn Viewers", ".plf", "application/vnd.pocketlearn"),
	pnm ("Portable Anymap Image", ".pnm", "image/x-portable-anymap"),
	pbm ("Portable Bitmap Format", ".pbm", "image/x-portable-bitmap"),
	pcf ("Portable Compiled Format", ".pcf", "application/x-font-pcf"),
	pfr ("Portable Font Resource", ".pfr", "application/font-tdpfr"),
	pgn ("Portable Game Notation (Chess Games)", ".pgn", "application/x-chess-pgn"),
	pgm ("Portable Graymap Format", ".pgm", "image/x-portable-graymap"),
	png ("Portable Network Graphics (PNG)", ".png", "image/png"),
	ppm ("Portable Pixmap Format", ".ppm", "image/x-portable-pixmap"),
	pskcxml ("Portable Symmetric Key Container", ".pskcxml", "application/pskc+xml"),
	pml ("PosML", ".pml", "application/vnd.ctc-posml"),
	ai ("PostScript", ".ai", "application/postscript"),
	pfa ("PostScript Fonts", ".pfa", "application/x-font-type1"),
	pbd ("PowerBuilder", ".pbd", "application/vnd.powerbuilder6"),
	pgp ("Pretty Good Privacy", ".pgp", "application/pgp-encrypted"),
	pgp2 ("Pretty Good Privacy - Signature", ".pgp", "application/pgp-signature"),
	box ("Preview Systems ZipLock/VBox", ".box", "application/vnd.previewsystems.box"),
	ptid ("Princeton Video Image", ".ptid", "application/vnd.pvi.ptid1"),
	pls ("Pronunciation Lexicon Specification", ".pls", "application/pls+xml"),
	str ("Proprietary P&G Standard Reporting System", ".str", "application/vnd.pg.format"),
	ei6 ("Proprietary P&G Standard Reporting System", ".ei6", "application/vnd.pg.osasli"),
	dsc ("PRS Lines Tag", ".dsc", "text/prs.lines.tag"),
	psf ("PSF Fonts", ".psf", "application/x-font-linux-psf"),
	qps ("PubliShare Objects", ".qps", "application/vnd.publishare-delta-tree"),
	wg ("Qualcomm's Plaza Mobile Internet", ".wg", "application/vnd.pmi.widget"),
	qxd ("QuarkXpress", ".qxd", "application/vnd.quark.quarkxpress"),
	esf ("QUASS Stream Player", ".esf", "application/vnd.epson.esf"),
	msf ("QUASS Stream Player", ".msf", "application/vnd.epson.msf"),
	ssf ("QUASS Stream Player", ".ssf", "application/vnd.epson.ssf"),
	qam ("QuickAnime Player", ".qam", "application/vnd.epson.quickanime"),
	qfx ("Quicken", ".qfx", "application/vnd.intu.qfx"),
	qt ("Quicktime Video", ".qt", "video/quicktime"),
	rar ("RAR Archive", ".rar", "application/x-rar-compressed"),
	ram ("Real Audio Sound", ".ram", "audio/x-pn-realaudio"),
	rmp ("Real Audio Sound", ".rmp", "audio/x-pn-realaudio-plugin"),
	rsd ("Really Simple Discovery", ".rsd", "application/rsd+xml"),
	rm ("RealMedia", ".rm", "application/vnd.rn-realmedia"),
	bed ("RealVNC", ".bed", "application/vnd.realvnc.bed"),
	mxl ("Recordare Applications", ".mxl", "application/vnd.recordare.musicxml"),
	musicxml ("Recordare Applications", ".musicxml", "application/vnd.recordare.musicxml+xml"),
	rnc ("Relax NG Compact Syntax", ".rnc", "application/relax-ng-compact-syntax"),
	rdz ("RemoteDocs R-Viewer", ".rdz", "application/vnd.data-vision.rdz"),
	rdf ("Resource Description Framework", ".rdf", "application/rdf+xml"),
	rp9 ("RetroPlatform Player", ".rp9", "application/vnd.cloanto.rp9"),
	jisp ("RhymBox", ".jisp", "application/vnd.jisp"),
	rtf ("Rich Text Format", ".rtf", "application/rtf"),
	rtx ("Rich Text Format (RTF)", ".rtx", "text/richtext"),
	link66 ("ROUTE 66 Location Based Services", ".link66", "application/vnd.route66.link66+xml"),
	rss ("RSS - Really Simple Syndication", ".rss", "application/rss+xml"),
	xml2 ("RSS - Really Simple Syndication", ".xml", "application/rss+xml"),
	shf ("S Hexdump Format", ".shf", "application/shf+xml"),
	st ("SailingTracker", ".st", "application/vnd.sailingtracker.track"),
	svg ("Scalable Vector Graphics (SVG)", ".svg", "image/svg+xml"),
	sus ("ScheduleUs", ".sus", "application/vnd.sus-calendar"),
	sru ("Search/Retrieve via URL Response Format", ".sru", "application/sru+xml"),
	setpay ("Secure Electronic Transaction - Payment", ".setpay", "application/set-payment-initiation"),
	setreg ("Secure Electronic Transaction - Registration", ".setreg", "application/set-registration-initiation"),
	sema ("Secured eMail", ".sema", "application/vnd.sema"),
	semd ("Secured eMail", ".semd", "application/vnd.semd"),
	semf ("Secured eMail", ".semf", "application/vnd.semf"),
	see ("SeeMail", ".see", "application/vnd.seemail"),
	snf ("Server Normal Format", ".snf", "application/x-font-snf"),
	spq ("Server-Based Certificate Validation Protocol - Validation Policies - Request", ".spq", "application/scvp-vp-request"),
	spp ("Server-Based Certificate Validation Protocol - Validation Policies - Response", ".spp", "application/scvp-vp-response"),
	scq ("Server-Based Certificate Validation Protocol - Validation Request", ".scq", "application/scvp-cv-request"),
	scs ("Server-Based Certificate Validation Protocol - Validation Response", ".scs", "application/scvp-cv-response"),
	sdp ("Session Description Protocol", ".sdp", "application/sdp"),
	etx ("Setext", ".etx", "text/x-setext"),
	movie ("SGI Movie", ".movie", "video/x-sgi-movie"),
	ifm ("Shana Informed Filler", ".ifm", "application/vnd.shana.informed.formdata"),
	itp ("Shana Informed Filler", ".itp", "application/vnd.shana.informed.formtemplate"),
	iif ("Shana Informed Filler", ".iif", "application/vnd.shana.informed.interchange"),
	ipk ("Shana Informed Filler", ".ipk", "application/vnd.shana.informed.package"),
	tfi ("Sharing Transaction Fraud Data", ".tfi", "application/thraud+xml"),
	shar ("Shell Archive", ".shar", "application/x-shar"),
	rgb ("Silicon Graphics RGB Bitmap", ".rgb", "image/x-rgb"),
	slt ("SimpleAnimeLite Player", ".slt", "application/vnd.epson.salt"),
	aso ("Simply Accounting", ".aso", "application/vnd.accpac.simply.aso"),
	imp ("Simply Accounting - Data Import", ".imp", "application/vnd.accpac.simply.imp"),
	twd ("SimTech MindMapper", ".twd", "application/vnd.simtech-mindmapper"),
	csp ("Sixth Floor Media - CommonSpace", ".csp", "application/vnd.commonspace"),
	saf ("SMAF Audio", ".saf", "application/vnd.yamaha.smaf-audio"),
	mmf ("SMAF File", ".mmf", "application/vnd.smaf"),
	spf ("SMAF Phrase", ".spf", "application/vnd.yamaha.smaf-phrase"),
	teacher ("SMART Technologies Apps", ".teacher", "application/vnd.smart.teacher"),
	svd ("SourceView Document", ".svd", "application/vnd.svd"),
	r2w ("Reflections Terminal Emulation", ".r2w", "application/x-reflection-vt"),
	rq ("SPARQL - Query", ".rq", "application/sparql-query"),
	srx ("SPARQL - Results", ".srx", "application/sparql-results+xml"),
	gram ("Speech Recognition Grammar Specification", ".gram", "application/srgs"),
	grxml ("Speech Recognition Grammar Specification - XML", ".grxml", "application/srgs+xml"),
	ssml ("Speech Synthesis Markup Language", ".ssml", "application/ssml+xml"),
	skp ("SSEYO Koan Play File", ".skp", "application/vnd.koan"),
	sgml ("Standard Generalized Markup Language (SGML)", ".sgml", "text/sgml"),
	sdc ("StarOffice - Calc", ".sdc", "application/vnd.stardivision.calc"),
	sda ("StarOffice - Draw", ".sda", "application/vnd.stardivision.draw"),
	sdd ("StarOffice - Impress", ".sdd", "application/vnd.stardivision.impress"),
	smf ("StarOffice - Math", ".smf", "application/vnd.stardivision.math"),
	sdw ("StarOffice - Writer", ".sdw", "application/vnd.stardivision.writer"),
	sgl ("StarOffice - Writer (Global)", ".sgl", "application/vnd.stardivision.writer-global"),
	sm ("StepMania", ".sm", "application/vnd.stepmania.stepchart"),
	sit ("Stuffit Archive", ".sit", "application/x-stuffit"),
	sitx ("Stuffit Archive", ".sitx", "application/x-stuffitx"),
	sdkm ("SudokuMagic", ".sdkm", "application/vnd.solent.sdkm+xml"),
	xo ("Sugar Linux Application Bundle", ".xo", "application/vnd.olpc-sugar"),
	au ("Sun Audio - Au file format", ".au", "audio/basic"),
	wqd ("SundaHus WQ", ".wqd", "application/vnd.wqd"),
	sis ("Symbian Install Package", ".sis", "application/vnd.symbian.install"),
	smi ("Synchronized Multimedia Integration Language", ".smi", "application/smil+xml"),
	xsm ("SyncML", ".xsm", "application/vnd.syncml+xml"),
	bdm ("SyncML - Device Management", ".bdm", "application/vnd.syncml.dm+wbxml"),
	xdm ("SyncML - Device Management", ".xdm", "application/vnd.syncml.dm+xml"),
	sv4cpio ("System V Release 4 CPIO Archive", ".sv4cpio", "application/x-sv4cpio"),
	sv4crc ("System V Release 4 CPIO Checksum Data", ".sv4crc", "application/x-sv4crc"),
	sbml ("Systems Biology Markup Language", ".sbml", "application/sbml+xml"),
	tsv ("Tab Seperated Values", ".tsv", "text/tab-separated-values"),
	tiff ("Tagged Image File Format", ".tiff", "image/tiff"),
	tao ("Tao Intent", ".tao", "application/vnd.tao.intent-module-archive"),
	tar ("Tar File (Tape Archive)", ".tar", "application/x-tar"),
	tcl ("Tcl Script", ".tcl", "application/x-tcl"),
	tex ("TeX", ".tex", "application/x-tex"),
	tfm ("TeX Font Metric", ".tfm", "application/x-tex-tfm"),
	tei ("Text Encoding and Interchange", ".tei", "application/tei+xml"),
	txt ("Text File", ".txt", "text/plain"),
	dxp ("TIBCO Spotfire", ".dxp", "application/vnd.spotfire.dxp"),
	sfs ("TIBCO Spotfire", ".sfs", "application/vnd.spotfire.sfs"),
	tsd ("Time Stamped Data Envelope", ".tsd", "application/timestamped-data"),
	tpt ("TRI Systems Config", ".tpt", "application/vnd.trid.tpt"),
	mxs ("Triscape Map Explorer", ".mxs", "application/vnd.triscape.mxs"),
	t ("troff", ".t", "text/troff"),
	tra ("True BASIC", ".tra", "application/vnd.trueapp"),
	ttf ("TrueType Font", ".ttf", "application/x-font-ttf"),
	ttl ("Turtle (Terse RDF Triple Language)", ".ttl", "text/turtle"),
	umj ("UMAJIN", ".umj", "application/vnd.umajin"),
	uoml ("Unique Object Markup Language", ".uoml", "application/vnd.uoml+xml"),
	unityweb ("Unity 3d", ".unityweb", "application/vnd.unity"),
	ufd ("Universal Forms Description Language", ".ufd", "application/vnd.ufdl"),
	uri ("URI Resolution Services", ".uri", "text/uri-list"),
	utz ("User Interface Quartz - Theme (Symbian)", ".utz", "application/vnd.uiq.theme"),
	ustar ("Ustar (Uniform Standard Tape Archive)", ".ustar", "application/x-ustar"),
	uu ("UUEncode", ".uu", "text/x-uuencode"),
	vcs ("vCalendar", ".vcs", "text/x-vcalendar"),
	vcf ("vCard", ".vcf", "text/x-vcard"),
	vcd ("Video CD", ".vcd", "application/x-cdlink"),
	vsf ("Viewport+", ".vsf", "application/vnd.vsf"),
	wrl ("Virtual Reality Modeling Language", ".wrl", "model/vrml"),
	vcx ("VirtualCatalog", ".vcx", "application/vnd.vcx"),
	mts ("Virtue MTS", ".mts", "model/vnd.mts"),
	vtu ("Virtue VTU", ".vtu", "model/vnd.vtu"),
	vis ("Visionary", ".vis", "application/vnd.visionary"),
	viv ("Vivo", ".viv", "video/vnd.vivo"),
	ccxml ("Voice Browser Call Control", ".ccxml", "application/ccxml+xml,"),
	vxml ("VoiceXML", ".vxml", "application/voicexml+xml"),
	src ("WAIS Source", ".src", "application/x-wais-source"),
	wbxml ("WAP Binary XML (WBXML)", ".wbxml", "application/vnd.wap.wbxml"),
	wbmp ("WAP Bitamp (WBMP)", ".wbmp", "image/vnd.wap.wbmp"),
	wav ("Waveform Audio File Format (WAV)", ".wav", "audio/x-wav"),
	davmount ("Web Distributed Authoring and Versioning", ".davmount", "application/davmount+xml"),
	woff ("Web Open Font Format", ".woff", "application/x-font-woff"),
	wspolicy ("Web Services Policy", ".wspolicy", "application/wspolicy+xml"),
	webp ("WebP Image", ".webp", "image/webp"),
	wtb ("WebTurbo", ".wtb", "application/vnd.webturbo"),
	wgt ("Widget Packaging and XML Configuration", ".wgt", "application/widget"),
	hlp ("WinHelp", ".hlp", "application/winhlp"),
	wml ("Wireless Markup Language (WML)", ".wml", "text/vnd.wap.wml"),
	wmls ("Wireless Markup Language Script (WMLScript)", ".wmls", "text/vnd.wap.wmlscript"),
	wmlsc ("WMLScript", ".wmlsc", "application/vnd.wap.wmlscriptc"),
	wpd ("Wordperfect", ".wpd", "application/vnd.wordperfect"),
	stf ("Worldtalk", ".stf", "application/vnd.wt.stf"),
	wsdl ("WSDL - Web Services Description Language", ".wsdl", "application/wsdl+xml"),
	xbm ("X BitMap", ".xbm", "image/x-xbitmap"),
	xpm ("X PixMap", ".xpm", "image/x-xpixmap"),
	xwd ("X Window Dump", ".xwd", "image/x-xwindowdump"),
	der ("X.509 Certificate", ".der", "application/x-x509-ca-cert"),
	fig ("Xfig", ".fig", "application/x-xfig"),
	xhtml ("XHTML - The Extensible HyperText Markup Language", ".xhtml", "application/xhtml+xml"),
	xml3 ("XML - Extensible Markup Language", ".xml", "application/xml"),
	xdf ("XML Configuration Access Protocol - XCAP Diff", ".xdf", "application/xcap-diff+xml"),
	xenc ("XML Encryption Syntax and Processing", ".xenc", "application/xenc+xml"),
	xer ("XML Patch Framework", ".xer", "application/patch-ops-error+xml"),
	rl ("XML Resource Lists", ".rl", "application/resource-lists+xml"),
	rs ("XML Resource Lists", ".rs", "application/rls-services+xml"),
	rld ("XML Resource Lists Diff", ".rld", "application/resource-lists-diff+xml"),
	xslt ("XML Transformations", ".xslt", "application/xslt+xml"),
	xop ("XML-Binary Optimized Packaging", ".xop", "application/xop+xml"),
	xpi ("XPInstall - Mozilla", ".xpi", "application/x-xpinstall"),
	xspf ("XSPF - XML Shareable Playlist Format", ".xspf", "application/xspf+xml"),
	xul ("XUL - XML User Interface Language", ".xul", "application/vnd.mozilla.xul+xml"),
	xyz ("XYZ File Format", ".xyz", "chemical/x-xyz"),
	yaml ("YAML Ain't Markup Language / Yet Another Markup Language", ".yaml", "text/yaml"),
	yang ("YANG Data Modeling Language", ".yang", "application/yang"),
	yin ("YIN (YANG - XML)", ".yin", "application/yin+xml"),
	zir ("Z.U.L. Geometry", ".zir", "application/vnd.zul"),
	zip ("Zip Archive", ".zip", "application/zip"),
	zmm ("ZVUE Media Manager", ".zmm", "application/vnd.handheld-entertainment+xml"),
	zaz ("Zzazz Deck", ".zaz", "application/vnd.zzazz.deck+xml");

	
	
	private String name;
	private String fileExtension;
	private String mimeType;

	
	
	private MimeTypesEnum(String anEnglishName, String aFileExtension, String aMimeType) {
		name = anEnglishName;
		fileExtension = aFileExtension;
		mimeType = aMimeType;
	}



	public String getName() {
		return name;
	}



	public String getFileExtension() {
		return fileExtension;
	}



	public String getMimeType() {
		return mimeType;
	}

	
	
	/**
	 * Find the MimeTypesEnum for the given MIME type aka HTML content type
	 * 
	 * @param aMimeType
	 * @return
	 */
	public static MimeTypesEnum valueOfMimeType(String aMimeType) {
		MimeTypesEnum answer = null;
		if (aMimeType != null && !aMimeType.trim().equalsIgnoreCase("")) {
			aMimeType = aMimeType.trim();
			for (MimeTypesEnum mime : MimeTypesEnum.values()) {
				if (aMimeType.equalsIgnoreCase(mime.getMimeType())) {
					answer = mime;
					break;
				}
			} // for
		} // if aMimeType
		return answer;
	}

	

	/**
	 * Find the MimeTypesEnum for the given file type
	 * 
	 * @param aFileType
	 * @return
	 */
	public static MimeTypesEnum valueOfFileType(String aFileType) {
		MimeTypesEnum answer = null;
		if (aFileType != null && !aFileType.trim().equalsIgnoreCase("")) {
			aFileType = aFileType.trim();
			for (MimeTypesEnum mime : MimeTypesEnum.values()) {
				if (aFileType.equalsIgnoreCase(mime.getFileExtension())) {
					answer = mime;
					break;
				}
			} // for
		} // if aFileType
		return answer;
	}
}
